[2022-06-23 17:58:25,767] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process-food-waste-data.process_data_task manual__2022-06-23T17:58:20.463145+00:00 [queued]>
[2022-06-23 17:58:25,772] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process-food-waste-data.process_data_task manual__2022-06-23T17:58:20.463145+00:00 [queued]>
[2022-06-23 17:58:25,773] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 17:58:25,773] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-23 17:58:25,773] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 17:58:25,783] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): process_data_task> on 2022-06-23 17:58:20.463145+00:00
[2022-06-23 17:58:25,788] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-06-23 17:58:25,788] {standard_task_runner.py:52} INFO - Started process 188 to run task
[2022-06-23 17:58:25,791] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process-food-waste-data', 'process_data_task', 'manual__2022-06-23T17:58:20.463145+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/02_data_process_dag.py', '--cfg-path', '/tmp/tmp56zher3j', '--error-file', '/tmp/tmpftss0xln']
[2022-06-23 17:58:25,791] {standard_task_runner.py:80} INFO - Job 300: Subtask process_data_task
[2022-06-23 17:58:25,824] {task_command.py:370} INFO - Running <TaskInstance: process-food-waste-data.process_data_task manual__2022-06-23T17:58:20.463145+00:00 [running]> on host fef44d313f22
[2022-06-23 17:58:25,875] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process-food-waste-data
AIRFLOW_CTX_TASK_ID=process_data_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-23T17:58:20.463145+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-23T17:58:20.463145+00:00
[2022-06-23 17:58:25,876] {logging_mixin.py:115} INFO - ENTERED FUNCTION
[2022-06-23 17:58:30,698] {logging_mixin.py:115} INFO - Row(id='5e31d5503b85a2e63d634187', date_collected=datetime.date(2020, 1, 27), retailer_type='counter service', retailer_detail='ready-to-eat and prepackaged health food', food_type='ready-to-eat', food_detail='organic oatmeal', label_type='sticker', label_language='use by', label_date='2020-01-28', approximate_dollar_value=5.25, image_id='IMG_1872', collection_lat=40.69453, collection_long=-73.99447, label_explanation='')
[2022-06-23 17:58:30,698] {python.py:173} INFO - Done. Returned value was: None
[2022-06-23 17:58:30,709] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=process-food-waste-data, task_id=process_data_task, execution_date=20220623T175820, start_date=20220623T175825, end_date=20220623T175830
[2022-06-23 17:58:30,737] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-23 17:58:30,762] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
